### ISSUE TITLE
"This add-on could not be installed because it appears to be corrupt."

### ISSUE THREAD

**Issue by groovecoder** [mozilla-services/sign-xpi#11]
I tried following https://mana.mozilla.org/wiki/display/SVCOPS/Sign+a+Mozilla+Internal+Extension to sign an `.xpi` ...

```
(sign-xpi)groovecoder:cli lcrouch$ sign-xpi -t mozillaextension -e stage -s net-mozaws-stage-addons-signxpi-input ~/code/testpilot-containers/testpilot-containers-2.3.0.xpi
{"uploaded": {"bucket": "net-mozaws-stage-addons-signxpi-output", "key": "testpilot-containers-2.3.0.xpi"}}
(sign-xpi)groovecoder:cli lcrouch$ aws s3 cp s3://net-mozaws-stage-addons-signxpi-output/testpilot-containers-2.3.0.xpi .
download: s3://net-mozaws-stage-addons-signxpi-output/testpilot-containers-2.3.0.xpi to ./testpilot-containers-2.3.0.xpi
```

but when I installed it into a fresh Firefox 54 profile, I got:

"This add-on could not be installed because it appears to be corrupt."

**Comment by groovecoder** [comment]
Note: using the prod environment seemed to work. So maybe this only affects stage?

**Comment by andymckay** [comment]
Did you set the about:config pref xpinstall.signatures.dev-root? You will need to be running Nightly to set that value and it take effect. When that is set add-ons signed with the prod cert will not work.

**Comment by groovecoder** [comment]
Good call. We should add that to the https://mana.mozilla.org/wiki/display/SVCOPS/Sign+a+Mozilla+Internal+Extension#SignaMozillaInternalExtension-Stage section.

**Comment by groovecoder** [comment]
And I mean - someone *else* should, because I don't seem to have access to edit that page.

**Comment by andymckay** [comment]
It might be better here: https://wiki.mozilla.org/Add-ons/Extension_Signing

The only people that really use this are QA and just the occasional tester.

**Comment by jasonthomas** [comment]
> Good call. We should add that to the https://mana.mozilla.org/wiki/display/SVCOPS/Sign+a+Mozilla+Internal+Extension#SignaMozillaInternalExtension-Stage section.

I've added a note there.

**Comment by groovecoder** [comment]
Cool, thanks.
