### ISSUE TITLE
Let's not sign a non-e10s extension

### ISSUE THREAD

**Issue by andymckay** [mozilla-services/sign-xpi#16]
Just to be sure we don't allow a legacy mozilla internal extension out into the wild that's not e10s compatible.

**Comment by glasserc** [comment]
How can I detect (in code) that an extension is non-e10s?

**Comment by andymckay** [comment]
Its only relevant for legacy extensions that have an install.rdf, they must have:

```<em:multiprocessCompatible>true</em:multiprocessCompatible>```

https://developer.mozilla.org/en-US/Add-ons/Install_Manifests#multiprocessCompatible

**Comment by glasserc** [comment]
I drn't think this is relevant any more, since e10s is everywhere.
